# A. Enunciado de la práctica

## 1. Objetivos de la práctica
El desarrollo de esta práctica pretende que el alumnado analice, diseñe e implemente soluciones a un problema usando las técnicas de aprendizaje automático y redes neuronales impartidas en la asignatura Inteligencia Artificial (IA). Para ello, el alumnado desarrollará de forma grupal (por cuartetos) un proyecto de programación en lenguaje Python mediante el uso del entorno de programación Google Colab y cuadernos de Python.

## 2. Caso de estudio
Se pretende resolver un problema de clasificación de especies de flores. Dadas las variables numéricas `sepal_length`, `sepal_width`, `petal_length` y `petal_width` se pretende encontrar la variable `species`. Este problema es típico en clasificación donde utilizando un número de mediciones se pretende dar una respuesta categórica.

Para resolver este problema se propone el uso de una red de neuronas artificial. En particular, de un **perceptrón multicapa** que recibirá como entrada las cuatro variables y como salida obtendrá la especie de la planta.

Para ello se proporciona un conjunto de datos a continuación:


In [1]:
!wget https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv

--2025-01-12 00:10:49--  https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3858 (3.8K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   3.77K  --.-KB/s    in 0s      

2025-01-12 00:10:49 (48.6 MB/s) - ‘iris.csv’ saved [3858/3858]



In [2]:
# Carga de los datos
import pandas as pd
pd.read_csv('iris.csv')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## 3. Desarrollo
El desarrollo de esta práctica supone completar este cuaderno de python para resolver el problema entrenando una red neuronal. Para ello debes seguir los siguientes pasos:


1.   Preprocesado
2.   Entrenamiento
3.   Evaluación

A continuación se describen los pasos pedidos en detalle.

### 3.1 Preprocesado

El preprocesado necesario en este problema es el siguiente: 1) Normalización de las variables de entrada. 2) Particionado entre entrenamiento, validación y test. 3) Aleatorización de los ejemplos de datos en el conjunto de entrenamiento.

1.    Se normalizará en el rango $[0, 1]$ de tal manera que cada variable sea transofmada mediate la expresión:
$$ x'_i = \frac{x_i - x_{min}}{x_{max} - x_{min}}  $$
donde $x$ es una variable de entre las variables elegidas para el problema.
2.    Se desarrollará una función que, dada una semilla aleatoria, obtenga un 80% de datos para entrenamiento, un 10% para validación y un 10% para test. No es necesario estratificar ya que los datos están balanceados.

### 3.2 Entrenamiento

Se debe implementar la red neuronal al completo. Se realizará un perceptrón multicapa en el que se probará con un número de capas ocultas igual a $L=\{1,2,4\}$ y con un número de neuronas en la(s) capa(s) oculta(s) igual a $H=\{2,32,512\}$. Se debe implementar en su totalidad las funcionalidades de **propagación hacia adelante** y el algoritmo de **backpropagation**, así como el bucle de entrenamiento. Se seguirá el paso de aprendizaje como:
1.   Cargar un ejemplo de datos
2.   Separar etiqueta ($y_i$) de variables ($x_i$) para el ejemplo $i$
3.   Computar $y'_i = f(x_i)$ donde $f$ es la red neuronal y $y'_i$ es la salida predicha.
4.   Comparar $l(y_i, y'_i)=y_i-y'_i$ para sacar la pérdida.
5.   Computar la actualización de los pesos mediante backpropagation
6.   Actualizar los pesos

Y el proceso de aprendizaje como:
1.   Ciclo de entrenamiento
2.   Ciclo de validación
3.   Repetir 1 y 2 durante X epochs.

### 3.3 Evaluación

Se debe implementar al menos la métrica Accuracy y calcularla con los datos del conjunto de test. Se podrán implementar otras métricas que se considere necesario.


### Experimentación

Dada la naturaleza estocástico de los algoritmos neuronales, cada configuración deberá ser evaluada al menos 5 veces con distintos números aleatorios (semillas). Se debe mostrar exclusivamente la media del Accuracy de cinco entrenamientos sobre el conjunto de Test.

Se probará con un número de capas ocultas igual a $L=\{1,2,4\}$ y con un número de neuronas en la(s) capa(s) oculta(s) igual a $H=\{2,32,512\}$. $α=0.5$ y 25 épocas.

Estas configuraciones pueden dar buenos o malos resultados, apuntad el resultado y considerad como acabado el experimento cuando concluyan. Las métricas deben calcularse como la media de 5 ejecuciones con diferentes semillas.

Para cada configuración propuesta se debe proporcionar una tabla de estas características (Puede usarse un generador de tablas https://www.tablesgenerator.com/markdown_tables o pandas https://pandas.pydata.org/docs/user_guide/index.html):

| HxL | 1   | 3   | 5   | 10  |
|-----|-----|-----|-----|-----|
| 1   | 50% | 50% | 50% | 50% |
| 4   | 50% | 50% | 50% | 50% |
| 8   | 50% | 50% | 50% | 50% |
| 100 | 50% | 50% | 50% | 50% |

## 4. Normativa de la práctica
Para el desarrollo del proyecto de programación se proporciona este cuaderno que sirve a modo de proyecto de programación. Se permiten crear todas las funciones adicionales que sea necesario siempre y cuando se respete la estructura general de este cuaderno. Este cuaderno es el único entregable, por tanto desarrollar código fuera de él no es recomendable.

Será necesario realizar una comparativa de resultados en una o varias tablas, así como incluir unas conclusiones al respecto.

La práctica debe realizarse teniendo en cuenta la siguiente normativa:
* NO está permitido alterar los nombres, parámetros ni tipo de retorno de ninguno de los métodos proporcionados. El método modificado se evaluará como 0 así como todos los métodos que dependan de él.
* No está permitido el uso de librerías externas excepto numpy y pandas. El uso de librerías externas hará que se evalúe la práctica como 0.
* La práctica se realizará de forma grupal (grupos de 4 alumnos). Cada grupo deberá desarrollar de manera independiente su propia práctica y realizar su propia entrega.
* El plagio de la práctica queda estrictamente prohibido. La detección de plagio supondrá una calificación de 0 en la convocatoria de la asignatura para todos los alumnos implicados, así como la posibilidad de apertura de expediente académico disciplinar.
* Para ser evaluado de la práctica es obligatorio entregarla en plazo, habiendo realizado correctamente al menos una funcionalidad de las pedidas. Una entrega fuera de plazo será evaluada como 0.
* Usa este cuaderno a modo de memoria, justificando las decisiones que tomes a lo largo del proceso de desarrollo. El desarrollo en texto puntúa de cara a la nota de la práctica.
* De cara a la entrega es estrictamente necesario entregar el cuaderno ejecutado al completo. Una entrega que no haya sido ejecutada con éxito hasta la última celda será evaluada como 0. (Entregad el archivo .ipynb)
* Se debe comentar el código adecuadamente. Este apartado es puntuable.
* Esta practica es OPCIONAL y solo será valorada si el alumno tiene 5 puntos o más en la asignatura.

# Cuerpo de la práctica
Usa las siguientes celdas para desarrollar todo el código pedido. Recuerda respetar esta estructura general y añadir celdas siempre dentro de cada apartado.

## Preprocesado

In [3]:
!wget https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv

--2025-01-12 00:10:50--  https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3858 (3.8K) [text/plain]
Saving to: ‘iris.csv.1’

iris.csv.1          100%[===================>]   3.77K  --.-KB/s    in 0s      

2025-01-12 00:10:50 (33.2 MB/s) - ‘iris.csv.1’ saved [3858/3858]



In [4]:
# Carga de los datos
import pandas as pd
import numpy as np

dataset = pd.read_csv('iris.csv')
dataset

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Primero normaliza los datos, usa la formula: $$ x'_i = \frac{x_i - x_{min}}{x_{max} - x_{min}}  $$
*   `normalize_variable` normaliza solo una columna de pandas
*   `normalize_dataset` normaliza solo las columnas indicadas en variables





In [5]:
VARIABLES = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

def normalize_variable(pandas_column):
  max = pandas_column.max()
  min = pandas_column.min()
  pandas_column = (pandas_column - min) / (max - min)
  return pandas_column

def normalize_dataset(pandas_dataset, variables=VARIABLES):
  # Hacemos una copia para no modificar el dataset original
  norm_df = pandas_dataset.copy()
  for var in variables:
    norm_df[var] = normalize_variable(norm_df[var])
  return norm_df

La funcion `train_test_val` divide los datos de tal manera que:


*   $N$ = nº Elementos del conjunto de datos completo
*   $N · p_{val} $ = nº Elementos del conjunto de validacion
*   $N · p_{test} $ = nº Elementos del conjunto de test
*   $N · (1 - p_{val} - p_{test})$ = nº Elementos del conjunto de entrenamiento

La función devolverá los conjuntos `train`, `test`, `val` ya particionados, y además aleatorizados.



In [6]:
def train_test_val(pandas_dataset, p_test, p_val, random_state=42):
  # Particionado entre train, test y validacion
  total_samples = len(pandas_dataset)
  test_size = int(total_samples * p_test)
  val_size = int(total_samples * p_val)

  # Aleatorizamos
  df = pandas_dataset.sample(frac=1)


  return df[0:test_size].reset_index(drop=True), df[test_size:test_size + val_size].reset_index(drop=True), df[test_size + val_size:].reset_index(drop=True)

¡`preprocess` integra los anteriores apartados!

In [7]:
def preprocess(pandas_dataset, p_test, p_val, random_state=42, variables=VARIABLES, label='species'):
  pandas_dataset = normalize_dataset(pandas_dataset, variables)
  return train_test_val(pandas_dataset, p_test, p_val, random_state)

In [8]:
#Uso de preprocess
preprocess(dataset, .1, .1)

(    sepal_length  sepal_width  petal_length  petal_width     species
 0       0.444444     0.500000      0.644068     0.708333  versicolor
 1       0.444444     0.416667      0.694915     0.708333   virginica
 2       0.583333     0.333333      0.779661     0.833333   virginica
 3       0.361111     0.416667      0.593220     0.583333  versicolor
 4       0.083333     0.500000      0.067797     0.041667      setosa
 5       0.527778     0.333333      0.644068     0.708333   virginica
 6       0.666667     0.208333      0.813559     0.708333   virginica
 7       0.583333     0.500000      0.593220     0.583333  versicolor
 8       0.361111     0.291667      0.542373     0.500000  versicolor
 9       0.722222     0.458333      0.661017     0.583333  versicolor
 10      0.166667     0.458333      0.084746     0.000000      setosa
 11      0.666667     0.541667      0.796610     0.833333   virginica
 12      0.333333     0.916667      0.067797     0.041667      setosa
 13      0.750000   

## Programando la red neuronal

Estos son los pasos más delicados y sensibles a fallos de todo el cuaderno. Presta máxima atención a cada paso guiado para completar la práctica.

Al final de cada sección se proporcionan ejemplos de uso. No los borres y usalos para verificar que tu código está funcionando adecuadamente.

### Inicializado de la red

Vamos a utilizar una inicialización concreta que funciona bien con el problema dado. En concreto se llama 'Glorot normal'. Esta inicialización hace que los pesos tomen un valor en una distribución normal de $μ=0$ y $σ = \sqrt{\frac{2}{in+out}}$ de tal forma que todos los pesos tomarán un valor aleatorio. Para inicializar una matriz de pesos usa `init_weights(inp, outp)`

El resultado de `make_nn` será una red con $W$ y $θ$ tal que:
$$W = [W^{(0)}, W^{(1)}, ..., W^{(d)}]$$
$$θ = [θ^{(0)}, θ^{(1)}, ..., θ^{(d)}]$$

Donde $d$ es el número de capas menos uno


In [9]:
def init_weigths(inp, outp):
  # Glorot normal. No hace falta tocar esto!
  std = np.sqrt(2/(inp+outp))
  return np.random.normal(scale= std, size= (inp, outp))

def make_nn(input_size, depth, width, output_size):
  # Declarar pesos y sesgos para cada una de las capas (depth) con tantas
  # neuronas como width. Inicializa la serie con valores en una distribucion
  # Glorot normal. Asume que depth es el numero de capas ocultas y depth > 0.
  # Elige la estructura de datos más conveniente para almacenar pesos y sesgos
  network = {}
  network['weights'] = []
  network['biases'] = []
  network['depth'] = depth
  network['width'] = width
  network['input_size'] = input_size
  network['output_size'] = output_size

  # 1. Capa de entrada, W0 y TH0
  weights = init_weigths(input_size, output_size if depth == 0 else width)
  network['weights'].append(weights)
  network['biases'].append(np.zeros(output_size if depth == 0 else width))

  # 2. Capas ocultas, W1..WD-1 y TH1..THD-1 donde D es depth
  for i in range(depth - 2):
    weights = init_weigths(width, width)
    network['weights'].append(weights)
    network['biases'].append(np.zeros(width))

  # 3. Capa de salida, WD y THD donde D es depth
  if depth > 0:
    weights = init_weigths(width, output_size)
    network['weights'].append(weights)
    network['biases'].append(np.zeros(output_size))

  return network
  # Se devuelve una red neuronal con W y TH

In [10]:
# Ejemplo de llamada a make_nn
layers = make_nn(4, 1, 2, 3)
for i, weights in enumerate(layers['weights']):
  print(f'Layer {i}: shape {weights.shape}')
  for j in weights:
    print(j)

Layer 0: shape (4, 2)
[0.91031717 0.41333203]
[-0.5799792  -0.06018429]
[ 0.03602393 -1.25205322]
[-0.67906569  0.23536627]
Layer 1: shape (2, 3)
[-0.36723641 -0.15273832 -0.7984366 ]
[-0.97996457  0.92550668 -1.18446585]


### Calcular la propagación hacia adelante

Recuerda seguir la propagación hacia delante correctamente de acuerdo a las siguientes expresiones:
$$Y^{(0)} = X $$
$$Y^{(i+1)} = σ(Y^{(i)} W^{(i)} + θ^{(i)}) \forall i = 0 .. d$$
donde $d=$ depth, $σ=$ funcion sigmoidal, $Y^{(i)}=$ salida parcial de la capa $i$, $W^{(i)}=$ pesos en la capa $i$, $θ^{(i)}=$ umbral en la capa $i$.

Además de $Y^{(d+1)}$ debes devolver en la función `forward` una estructura que almacene:
$$Y = [Y^{(0)}, Y^{(1)}, ..., Y^{(d+1)}]$$

In [11]:
############################ NO TOCAR ####################################
def sig(x):
  # Funcion sigmoide que recibe el valor Y(i)W(i)+Theta(i) en x.
  return 1/(1+np.exp(-x.astype('float')))
############################ NO TOCAR ####################################

In [12]:
def forward(inputs, network, act= lambda x: x):
  # Hacer la pasada hacia delante. Almacena las salidas parciales de la red
  # en la estructura de datos que prefieras. Incluye también la entrada en
  # dicha estructura. [inputs, salida_1, ..., salida_depth] donde salida_depth
  # es la predicción.

  # 1. Y(0) = X
  # 2. Y(i+1) = sigmoid( Y(i) x W(i) + TH(i) ) foreach i in 0..d
  outputs = []
  outputs.append(inputs)

  for i in range(len(network['weights'])):
    num_neurons = len(network['weights'][i][0])
    output = np.zeros(num_neurons)
    for j in range(num_neurons):
      output[j] = act(np.dot(outputs[i], network['weights'][i][:,j]) + network['biases'][i][j])
    outputs.append(output)

  return outputs[-1], outputs

In [13]:
# Ejemplo de salida de forward
output, partials = forward(np.array([1,1,1,1]), layers, act=sig)
partials

[array([1, 1, 1, 1]),
 array([0.42245491, 0.33994503]),
 array([0.38030004, 0.56220021, 0.3230136 ])]

### Computar la propagación hacia atrás
**ATENCION**: Este es un paso MUY delicado.

El algoritmo de retropropagación para la regla delta generalizada es el siguiente:

1.   Contamos con $Y$ → extraemos $Y^{(d+1)}$
2.   Computamos la pérdida como $$V^{(d+1)} = D - Y^{(d+1)}$$ donde $D$ es un vector del mismo tamaño que la salida, que contiene las salidas deseadas. (*Aclaración*: en nuestro caso son salidas categóricas codificadas como un vector [0,0,1], [0,1,0] o [1,0,0] para cada tipo de flor)
3.   Computamos la regla delta usando $$f(y) = y · (1-y)$$
$$δ^{(d+1)} = V^{(d+1)} ⊙ f(Y^{(d+1)})$$
donde $f$ se proporciona en `sig_derivate(y)`. El operador ⊙ es el producto Hadamard (ejemplo: $(1,0,1) ⊙ (0,1,2) = (1·0, 0·1, 1·2) = (0, 0, 2)$)
4.   Las actualizaciones de los pesos se computan como
$$ΔW^{(d)} = α · Y^{(d)T}δ^{(d+1)}$$
$$Δθ^{(d)} = α · δ^{(d+1)}$$
5.   Los apartados anteriores se repiten para cada i igual a d hasta 1 de tal manera que se sigue la siguiente regla de la cadena:
$$V^{(i)} = δ^{(i+1)}W^{(i)T}$$
$$δ^{(i)} = V^{(i)} ⊙ f(Y^{(i)})$$
$$ΔW^{(i-1)} = α · Y^{(i-1)T}δ^{(i)}$$
$$Δθ^{(i-1)} = α · δ^{(i)}$$
$$ ∀i=d..1$$

El resultado serán las actualizaciones que almacenarás en una única estructura de datos:
$$ΔW = [ΔW^{(0)}, ΔW^{(1)}, ..., ΔW^{(d)}]$$
$$Δθ = [Δθ^{(0)}, Δθ^{(1)}, ..., Δθ^{(d)}]$$

### **Un apunte:** Las activaciones y sus derivadas
La derivada de la sigmoide ($σ$) es en realidad

$$σ'(x) = \frac{1}{1+e^{-x}} · (1 - \frac{1}{1+e^{-x}}) = σ(x) · (1-σ(x)) $$

de tal manera que para simplificar la operación utilizaremos $f(x)$

$$f(x) = x · (1-x)$$

a la que directamente podremos pasar $Y^{(i+1)} = σ(Y^{(i)}W^{(i)} + θ^{(i)})$ usando la expresion $f(Y^{(i)}) = σ'(Y^{(i)}W^{(i)} + θ^{(i)})$

Si se deseara usar otra funcion de activacion para la red, habría que utilizar una $g(x)$ y su derivada $g'(x)$, en vez de $σ(x)$ y $σ'(x)$ respectivamente.


In [14]:
############################ NO TOCAR ####################################
def sig_derivate(y):
  # Funcion sigmoide' que recibe el valor sigmoide(x) en y.
  return y.astype('float')*(1-y.astype('float'))
############################ NO TOCAR ####################################

In [43]:
def backward(desired, partials, network, alpha=1, rev_act= lambda x:x):
  # Computar backpropagation, almacenar cada delta de los pesos de tal
  # manera que se pueda actualizar los pesos durante el proceso de
  # aprendizaje. Desired es la salida deseada, otro vector.
  # partials contiene todas las salidas parciales usando la estructura
  # [inputs, salida_1, ..., salida_depth]

  updates = { 'weights': [], 'biases': []}

  # V(d+1) = D - Y(d+1)$$
  loss = desired - partials[-1]


  # foreach i in d+1..1
  for i in range(len(network['weights']), 0, -1):
  #   delta(i) = V(i) · sig_derivate(Y(i))
    delta = loss * rev_act(partials[i])
  #   dW(i-1) = lr · Y(i-1).T x delta(i)
    weight_updates = alpha * np.dot(partials[i-1].reshape(-1, 1), delta.reshape(1, -1))
  #   dTH(i-1) = lr · delta(i)
    bias_updates = alpha * delta
    updates['weights'].insert(0, weight_updates)
    updates['biases'].insert(0, bias_updates)
  #   V(i-1) = delta(i) x W(i).T
    loss = np.dot(delta, network['weights'][i - 1].T)

  return updates
  # Se devuelve una única estructura de datos con DW y DTH

In [44]:
# Ejemplo de salida de backward
updates = backward(np.array([1,0,0]), partials, layers, 1, rev_act=sig_derivate)
updates
print('Updates')
for i, weights in enumerate(updates['weights']):
  print(f'Layer {i}: shape {weights.shape}')
  for j in weights:
    print(j)
print('Biases')
for i, bias in enumerate(updates['biases']):
  print(f'Layer {i}: shape {bias.shape}')
  print(bias)


Updates
Layer 0: shape (4, 2)
[ 0.00583118 -0.04207657]
[ 0.00583118 -0.04207657]
[ 0.00583118 -0.04207657]
[ 0.00583118 -0.04207657]
Layer 1: shape (2, 3)
[ 0.0616978  -0.05845719 -0.02984021]
[ 0.04964757 -0.04703988 -0.02401211]
Biases
Layer 0: shape (2,)
[ 0.00583118 -0.04207657]
Layer 1: shape (3,)
[ 0.14604588 -0.13837498 -0.07063526]


### Actualizacion de los pesos
Usando las salidas de `backward(...)` y `network` que es la red entrenable, haremos la actualización de los pesos devolviendo una nueva red actualizada mediante la regla:
$$W^{(i)}(t+1) = W^{(i)}(t) + ΔW^{(i)}(t)$$
$$θ^{(i)}(t+1) = θ^{(i)}(t) + Δθ^{(i)}(t)$$

In [17]:
def update_weights(network, updates):
  # Actualizar la red almacenada en network usando los updates
  # Devuelve la red actualizada
  new_network = {}

  new_network['weights'] = []
  new_network['biases'] = []
  new_network['depth'] = network['depth']
  new_network['width'] = network['width']
  new_network['input_size'] = network['input_size']
  new_network['output_size'] = network['output_size']

  num_layers = len(network['weights'])

  for i in range(num_layers):
    new_network['weights'].append(network['weights'][i] + updates['weights'][i])
    new_network['biases'].append(network['biases'][i] + updates['biases'][i])


  # 1. W(i) += dW(i)
  # 2. TH(i) += dTH(i)

  return new_network
  # Se devuelve una red entera con W y TH

In [53]:
# Example of update_weights
new_layers = update_weights(layers, updates)
new_layers

{'weights': [array([[ 0.91614835,  0.37125546],
         [-0.57414801, -0.10226085],
         [ 0.04185511, -1.29412979],
         [-0.67323451,  0.1932897 ]]),
  array([[-0.30553861, -0.21119551, -0.82827682],
         [-0.930317  ,  0.87846679, -1.20847796]])],
 'biases': [array([ 0.00583118, -0.04207657]),
  array([ 0.14604588, -0.13837498, -0.07063526])],
 'depth': 1,
 'width': 2,
 'input_size': 4,
 'output_size': 3}

## Entrenamiento y Validación
Aquí vamos a hacer los pasos de entrenamiento, validación y su composición en una época completa.

El paso de entrenamiento es:


*   Del ejemplo extraemos los datos de entrada $X$ asi como la salida deseada $D$
*   La funcion `forward` que recibe $X$, ($W$, $θ$) y la función $σ$. Las salidas de forward son una tupla conteniendo $Y^{(d+1)}$ e $Y$, extrae $Y$
*   La funcion `backward` que recibe $D$, $Y$, ($W$, $θ$), $α$ y $σ'$. Las salidas de backward contienen una estructura con $ΔW$ y $Δθ$
*   La funcion `update_weights` que recibe ($W$, $θ$) y ($ΔW$ y $Δθ$)
*   Se devuelve la salida de la funcion **update_weights**



In [18]:
TO_ARR = {'versicolor': np.array([0,0,1]),
          'virginica': np.array([0,1,0]),
          'setosa': np.array([1,0,0]),
        } # Diccionario para pasar de categorico a one hot encoding!

def train_step(example, network, alpha=1):
  ## Usa las funciones definidas anteriormente para crear el paso de entrenamiento
  ## Devuelve una red actualizada
  desired = TO_ARR[example['species']]
  inputs = np.array([example['sepal_length'], example['sepal_width'], example['petal_length'], example['petal_width']])
  output, partials = forward(inputs, network, act=sig)
  updates = backward(desired, partials, network, alpha, rev_act=sig_derivate)
  new_network = update_weights(network, updates)

  # Extraer un ejemplo
  # Propagar hacia delante
  # Calcular loss y propagar hacia detras
  # Actualizar pesos

  return new_network
  # Se devuelve una red entera con W y TH

El paso de validacion es:
*   Del ejemplo extraemos los datos de entrada $X$ asi como la salida deseada $D$
*   La funcion `forward` que recibe $X$, ($W$, $θ$) y la función $σ$. Las salidas de forward son una tupla conteniendo $Y^{(d+1)}$ e $Y$, extrae $Y^{(d+1)}$
*   Se devuelve SOLO $Y^{(d+1)}$


In [19]:
def pred_step(example, network):
  ## Usa las funciones definidas para extraer un ejemplo y calcular su prediccion

  # Extraer un ejemplo
  # Propagar hacia delante
  inputs = np.array([example['sepal_length'], example['sepal_width'], example['petal_length'], example['petal_width']])
  output, partials = forward(inputs, network, act=sig)

  return output
  # Un vector con la predicción en bruto Y(d+1)

La epoca completa de entrenamiento es un bucle sencillo. Para cada ejemplo de entrenamiento se produce un paso de entrenamiento, simplemente. Haz todas las operaciones necesarias intermedias que consideres necesarias para iterar por todo el conjunto de datos y obtener un $X$ y un $D$.

Además se recomiendo extraer alguna métrica para evalual más adelante si está funcionando o no la red:


*   Usa `pred_step` para sacar una predicción
*   Puedes volver a medir el MAE del ejemplo $\sum^n_{j=1} \frac{1}{n}|D_j-Y_j^{(d+1)}|$ donde $n$ es el numero de etiquetas.

¡También puedes probar a medir el accuracy, o el f1-score!




In [51]:
def train_epoch(dataset, network, alpha=1):
  ## Bucle de entrenamiento. Si quieres puedes extraer métricas de entrenamiento
  metrics = []
  examples = dataset.to_dict('records')
  total_correct = 0
  mae = 0

  for example in examples:
    network = train_step(example, network, alpha)

    pred = pred_step(example, network)

    if np.argmax(pred) == np.argmax(TO_ARR[example['species']]):
      total_correct += 1

    mae += np.mean(np.abs(TO_ARR[example['species']] - pred))

  metrics.append((total_correct / len(examples)) * 100)
  metrics.append(mae)

  return network, metrics
  # Este método debe devolver la estructura que contenga la red neuronal y las metricas.

Esta es la época de validación, ahora no necesitas hacer un paso de entrenamiento, solo extraer predicciones y demás comprobaciones.

In [50]:
def valid_epoch(dataset, network):
  ## Bucle de validacion. Solo se extraen las metricas de validacion
  metrics = []
  examples = dataset.to_dict('records')
  total_correct = 0
  mae = 0

  for example in examples:
    pred = pred_step(example, network)

    if np.argmax(pred) == np.argmax(TO_ARR[example['species']]):
      total_correct += 1

    mae += np.mean(np.abs(TO_ARR[example['species']] - pred))

  metrics.append((total_correct / len(examples)) * 100)
  metrics.append(mae)

  return metrics
  # Este método debe devolver solo las metricas.

## Test

In [49]:
def test_epoch(dataset, network):
  metrics = []
  examples = dataset.to_dict('records')
  total_correct = 0
  mae = 0

  for example in examples:
    pred = pred_step(example, network)

    if np.argmax(pred) == np.argmax(TO_ARR[example['species']]):
      total_correct += 1

    mae += np.mean(np.abs(TO_ARR[example['species']] - pred))

  metrics.append((total_correct / len(examples)) * 100)
  metrics.append(mae)

  return metrics
  # Este método debe devolver solo las metricas.

## Entrenamiento completo
Ahora viene el gran paso: hacer un entrenamiento completo usando el método `run`.
El algoritmo es sencillo en este caso, para cada epoca dada en `epoch`, computar

1.   Una pasada de entrenamiento, devolviendo red y métricas
2.   Una pasada de validacion, devolviendo las métricas de validacion
3.   Imprimir por pantalla toda la informacion que se considere oportuna
4.   Finalizar bucle si se cumple criterio de parada, sino, repetir desde #1
5.   Computar las métricas de test y, si procede, imprimirlas
6.   Se devuelve solo las metricas de test


In [23]:
def logger(i, metrics, msg='', *args, **kwargs):
  # Imprime las metricas obtenidas para la epoch = i
  if len(metrics) > 0:
    print(f'{i}= {msg} - Acc: {metrics[0]}, Loss: {metrics[1]}')

In [37]:
def run(train, test, val, network, alpha=1, epochs=2, verbose=False):
  ## Bucle completo dado el numero de epochs.
  # 1. preprocess
  # 2. train/valid process
  # 3. test
  for i in range(epochs):
    network, train_metrics = train_epoch(train, network, alpha)
    valid_metrics = valid_epoch(val, network)
    if verbose:
      logger(i, train_metrics, 'train metrics')
      logger(i, valid_metrics, 'valid metrics')

  test_metrics = test_epoch(test, network)
  logger(i, test_metrics, 'test metrics')

  return test_metrics

# Experimentos
Usa la función `run_experiment` para extraer resultados.

## Utilidades
Usa el método `run_experiment` para lanzar los experimentos. Para que todo funcione correctamente cada parte anterior debe estar correctamente programada. Se recomienda hacer 5 ejecuciones que devuelven una lista con todas las metricas que se hayan descrito durante la ejecucion.

In [25]:
############################ NO TOCAR ####################################
def run_experiment(dataset, network_depth, network_width, alpha=1,
                   epochs=100, p_val=.1, p_test=.1, seeds=[1,2,3,4,5],
                   verbose=False):
  label = 'species'
  vars = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

  test_metrics = []

  for seed in seeds:
    set_seed(seed)
    output_size = len(dataset[label].unique())
    input_size = len(vars)
    network = make_nn(input_size, network_depth, network_width, output_size)
    train, test, val = preprocess(dataset, p_val, p_test, random_state=seed)

    test_metrics.append(run(train, test, val, network, alpha=alpha, epochs=epochs, verbose=verbose))

  return test_metrics # Se devuelve una lista de estructuras de datos conteniendo las metricas medidas

##########################################################################

### Generación de números aleatorios

In [26]:
import numpy as np
import random
def set_seed(seed):
    # Se debe fijar la semilla usada para generar números aleatorios
    # En la libreria random
    random.seed(seed)
    # En la libreria numpy
    np.random.seed(seed)

## Ejecuciones
Este espacio de la práctica está reservado a las ejecuciones de los algoritmos. Se recomienda el uso del método launch_experiment.

In [52]:
# Crear un conjunto de 5 semillas para los experimentos
seeds = [1234567890 + i*23 for i in range(5)] # Semillas de ejemplo, cambiar por las semillas que se quieran
run_experiment(dataset, 1, 1, alpha=0.1, epochs=100, seeds=seeds)

99= test metrics - Acc: 60.0, Loss: 6.437759797854431
99= test metrics - Acc: 26.666666666666668, Loss: 6.154575592423307
99= test metrics - Acc: 73.33333333333333, Loss: 6.17897877706531
99= test metrics - Acc: 40.0, Loss: 6.62767300525337
99= test metrics - Acc: 66.66666666666666, Loss: 5.798798863907102


[[60.0, 6.437759797854431],
 [26.666666666666668, 6.154575592423307],
 [73.33333333333333, 6.17897877706531],
 [40.0, 6.62767300525337],
 [66.66666666666666, 5.798798863907102]]

### Exploración de hiperparámetros

In [38]:
### Coloca aquí tus experimentos Width 2,32,512 Depth 1,2,4 ###
metrics = run_experiment(dataset, 2, 1, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 2 Depth 1 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 32, 1, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 32 Depth 1 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 512, 1, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 512 Depth 1 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)

metrics = run_experiment(dataset, 2, 2, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 2 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 32, 2, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 32 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 512, 2, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 512 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)

metrics = run_experiment(dataset, 2, 4, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 2 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 32, 4, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 32 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)
metrics = run_experiment(dataset, 512, 4, alpha=0.5, epochs=25, seeds=seeds)
print(f'Width 512 Depth 2 Accuracy: {np.array(metrics).mean(axis=0)[0]}')
print('='*80)


24= test metrics - Acc: 46.666666666666664, Loss: 0.3883105800703361
24= test metrics - Acc: 66.66666666666666, Loss: 0.4807536888774555
24= test metrics - Acc: 73.33333333333333, Loss: 0.5495665525029089
24= test metrics - Acc: 40.0, Loss: 0.4420419536294067
24= test metrics - Acc: 66.66666666666666, Loss: 0.540253366509383
Width 2 Depth 1 Accuracy: 58.66666666666665
24= test metrics - Acc: 26.666666666666668, Loss: 0.4102931796929237
24= test metrics - Acc: 40.0, Loss: 0.35842231807551195
24= test metrics - Acc: 26.666666666666668, Loss: 0.4552448305432501
24= test metrics - Acc: 26.666666666666668, Loss: 0.44339882899426075
24= test metrics - Acc: 20.0, Loss: 0.6485437717609733
Width 32 Depth 1 Accuracy: 28.0
24= test metrics - Acc: 40.0, Loss: 0.5453462242255327
24= test metrics - Acc: 40.0, Loss: 0.35074372044169766
24= test metrics - Acc: 46.666666666666664, Loss: 0.46514032359265894
24= test metrics - Acc: 33.33333333333333, Loss: 0.39925159892999695
24= test metrics - Acc: 40.0

**Resultados y Conclusiones**

| Neuronas \ Profundidad | 1  | 2  | 4  |
|------------------------|----|----|----|
| 2                      | 58 | 58 | 68 |
| 32                     | 28 | 37 | 32 |
| 512                    | 40 | 37 | 34 |

La tabla de resultados y una valoración crítica de los resultados. Incluye las conclusiones.

Los resultados parecen indicar que el número de neuronas y de layers no afecta demasiado a la accuracy.
También los malos resultados pueden indicar que hay algún error en el código, ya que es un dataset muy sencillo de predecir.